services:
  url_shortener:
    build:
      context: ../../
      dockerfile: projects/01_url_shortener/docker/Dockerfile
    ports:
      - "3005:3005"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/url_shortener
      - REDIS_URL=redis://redis:6379/
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=url_shortener
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
