services:
  prospect_web_crawler:
    build:
      context: ../../
      dockerfile: projects/02_prospect_web_crawler/docker/Dockerfile
    ports:
      - "3006:3006"
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/prospect_web_crawler
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=prospect_web_crawler
    ports:
      - "5432:5432" # Changed back to 5432
